### PR TITLE
withUAL Prop Fix

### LINKED ISSUE #46: withUAL HOC not passing props
Components wrapped with the [withUAL HOC](https://github.com/EOSIO/ual-reactjs-renderer/blob/master/src/components/provider/UALContext.js) do not properly pass props to the wrapped component.

### PR DESCRIPTION
**Pull request by TaraTritt**
- Closes #46 
- Adding tests for withUAL HOC and moving it to its own file
- Adding missing pull request template

### CODE REVIEW

File: __tests__/withUAL.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+  let wrappedComponent
+  let component
+  let name
+
+  beforeEach(() => {
+    component = (props) => {
+      return <h1>Hello, {props.name}</h1>;
+    }
+    name = 'testName'
+    const WithUALComponent = withUAL(component)
```
Comment (wpwood) [inline __tests__/withUAL.js]: Personal preference, but I'd just call that `WrappedComponent`

File: src/components/modal/UALBox.js [hunk 2]
```diff
@@ -4,7 +4,7 @@ import PropTypes from 'prop-types'
 import i18n from '../../i18n'
 
 import { UALContainer } from './UALContainer'
-import { withUAL } from '../provider/UALContext'
+import { withUAL } from '../provider/withUAL'
```
Comment (wpwood) [inline src/components/modal/UALBox.js]: To stay consistent, should this be `'../provider/WithUAL'`?

File: __tests__/withUAL.js (hunk 1 above)
Comment (TaraTritt) [reply __tests__/withUAL.js]: 👍

File: src/components/modal/UALBox.js (hunk 2 above)
Comment (TaraTritt) [reply src/components/modal/UALBox.js]: I think in this case since its only export is `withUAL`, which is not a class, I want to keep this file lowercase `withUAL` to match
